
export const BASKET_REQUEST = 'BASKET_REQUEST';
export const BASKET_SUCCESS = 'BASKET_SUCCESS';
export const BASKET_ERROR = 'BASKET_ERROR';

export const ADD_BASKET_REQUEST = 'ADD_BASKET_REQUEST';
export const ADD_BASKET_SUCCESS = 'ADD_BASKET_SUCCESS';
export const ADD_BASKET_ERROR = 'ADD_BASKET_ERROR';

export const REMOVE_BASKET_REQUEST = 'REMOVE_BASKET_REQUEST';
export const REMOVE_BASKET_ERROR = 'REMOVE_BASKET_ERROR';

export const CHANGE_BASKET_REQUEST = 'CHANGE_BASKET_REQUEST';
export const CHANGE_BASKET_SUCCESS = 'CHANGE_BASKET_SUCCESS';
export const CHANGE_BASKET_ERROR = 'CHANGE_BASKET_ERROR';
