
export const ORDERS_REQUEST = 'ORDERS_REQUEST';
export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
export const ORDERS_ERROR = 'ORDERS_ERROR';

export const ORDER_CONFIRM_REQUEST = 'ORDER_CONFIRM_REQUEST';
export const ORDER_CONFIRM_SUCCESS = 'ORDER_CONFIRM_SUCCESS';
export const ORDER_CONFIRM_ERROR = 'ORDER_CONFIRM_ERROR';
