
export const POPULAR_SHOPS_REQUEST = 'POPULAR_SHOPS_REQUEST';
export const POPULAR_SHOPS_SUCCESS = 'POPULAR_SHOPS_SUCCESS';
export const POPULAR_SHOPS_ERROR = 'POPULAR_SHOPS_ERROR';
export const SHOP_REQUEST = 'SHOP_REQUEST';
export const SHOP_SUCCESS = 'SHOP_SUCCESS';
export const SHOP_ERROR = 'SHOP_ERROR';
